### ISSUE TITLE
Add tests to ensure multiple/no generators are added correctly

### ISSUE THREAD

**Issue by sabinadams** [sabinadams/aurora#42]
**Describe the bug**
Need tests to cover the multiple/no generator scenario

**Expected behavior**
Test suite should include a test that checks that a schema with multiple generators will properly be handled. It should also test a schema with *no* generator, which should pass.

**Additional context**
PR #38 Added this enhancement

**Comment by codeninja** [comment]
So, just looking at this since I added the new feature, the renderBlock is adding the generator tag to the generator block which results in a double `generator generator GeneratorName`

![image](https://user-images.githubusercontent.com/14914/153037368-dece1b57-4bc6-4f5a-ad1d-c6a14c69aad7.png)

![image](https://user-images.githubusercontent.com/14914/153037389-57f9c60e-ce2a-4af7-8e5b-1deade2553fe.png)

![image](https://user-images.githubusercontent.com/14914/153037413-1c692abb-e011-463f-8c7c-434f6501d526.png)

![image](https://user-images.githubusercontent.com/14914/153037457-5235fee9-ac60-4a06-bf3c-b7dbaf6f3ca9.png)

**Comment by codeninja** [comment]
More info on comment above: 

Call stack: 
Aurora.ts -> renderGenerators -> renderBlock #extra generator inserted here as the name of the block.

**Comment by codeninja** [comment]
![image](https://user-images.githubusercontent.com/14914/153040389-bd7f7e8d-2827-4bb7-9a41-81cd519ccc35.png)
